version: "3"

services:
  socket:
    build:
      context: .
    container_name: socket
    ports:
      - "3001:3001"
      - "4000:4000"
    restart: always
    command:
      - "npm run start"
      - "npm run express"
